### ISSUE TITLE
Gracefully Handle Bounces using Zerobounce, Sparkpost Events API & Firebase Firestore database

### ISSUE THREAD

**Issue by ghousemohamed** [bigbinary/neeto_mail_interceptor#4]
When an email is scheduled to be sent, we will be checking with ZeroBounce to see if the email is valid or not as well as checking with our Firestore service to see if there are any past bounced records associated with this email. Only if these checks are passed we will be allowing the email to be sent. To do this, here's a list of points to keep in mind while implementing this:

1. ZeroBounce has many statuses that it returns during email validation. We can get a list of status codes mentioned by zerobounce here https://www.zerobounce.in/docs/email-list-validation/status-codes

- We are only going to consider, `valid`, `do_not_mail` statues (In do_not_mail type, we will only considering `role_based` and `disposable`)
- We will also query the Firestore DB to see if the email has any bounce records. If it does, then we will not be sending the email

2. We will be using SparkPost's Events API to see what all emails have bounced in the past days using a cronjob, and will be storing this in a firestore DB service. SparkPost Events API Documentation: https://developers.sparkpost.com/api/events/

- We need to have a cronjob in neetoAuth. which will be run on a daily basis. This will query the events API for all emails which have bounced in the last day.
- After getting the emails which have bounced in the last day, we should be  storing this email and attaching `bounced_at` timestamp along with it in the Firebase Firestore DB. If email is already present in firestore DB, then we should be updating this record in firestore DB. 

3. Firestore Database

- Once an email is invalid, or it has bounced or started to bounced, then we need to store this in the Firestore database with the `bounced_at` timestamp. Any email address cannot have more than 2 bounces.
- If the email is invalid during the ZeroBounce verification step, then also we will log this email address in our Firestore database.

Firestore document model schema:

```
EmailAddress (Document Name): {
email: string,
bounced_at_0: datetime,
bounced_at_1: datetime
}
```

@Nuzair46 _a

cc: @neerajdotname

**Comment by Nuzair46** [comment]
All PR's related to this issue is merged. 
Feature should be running for staging.
For production, setting up the api keys mentioned in the following PR's will enable it
https://github.com/bigbinary/neeto-auth-web/issues/2285
#17

**Comment by Nuzair46** [comment]
Keys are added for production apps except 
```
neeto-bugtrap
neeto-ci
neeto-monitor
neeto-popups
neeto-review
neeto-sign
neeto-site
```

**Comment by Nuzair46** [comment]
closing as this is live in production
